# Created at 2025-09-16T15:47:43.271
org.testng.TestNGException: 
Cannot instantiate class Testrunner.ParallelrunnerTest
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:43)
	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:18)
	at org.testng.internal.objects.SimpleObjectDispenser.instantiateUsingDefaultConstructor(SimpleObjectDispenser.java:179)
	at org.testng.internal.objects.SimpleObjectDispenser.createInstance(SimpleObjectDispenser.java:88)
	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:41)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispenseObject(GuiceBasedObjectDispenser.java:41)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:31)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:107)
	at org.testng.internal.ClassImpl.getObjects(ClassImpl.java:140)
	at org.testng.internal.IObject.lambda$objects$0(IObject.java:59)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.testng.internal.IObject.objects(IObject.java:59)
	at org.testng.TestClass.getObjects(TestClass.java:150)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:126)
	at org.testng.TestClass.init(TestClass.java:118)
	at org.testng.TestClass.<init>(TestClass.java:83)
	at org.testng.TestRunner.initMethods(TestRunner.java:473)
	at org.testng.TestRunner.init(TestRunner.java:347)
	at org.testng.TestRunner.init(TestRunner.java:302)
	at org.testng.TestRunner.<init>(TestRunner.java:176)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:636)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:197)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1365)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1339)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1199)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:40)
	... 34 more
Caused by: java.lang.Error: Unresolved compilation problems: 
	The import org.junit cannot be resolved
	The import io.cucumber.junit cannot be resolved
	RunWith cannot be resolved to a type
	Cucumber cannot be resolved to a type

	at Testrunner.ParallelrunnerTest.<init>(ParallelrunnerTest.java:3)
	... 40 more


